In [104]:
import pandas as pd

In [105]:
df = pd.read_csv("futball.csv")
display(df)

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
0,0,0,Mohamed Salah,Liverpool,Premier League,Forward,38,29,18,130,1450,1130,3378,77.931034,0.772647,47
1,1,1,Erling Haaland,Manchester City,Premier League,Forward,31,22,3,105,610,480,2773,78.688525,0.714028,25
2,2,2,Cole Palmer,Chelsea,Premier League,Midfielder,37,15,8,126,1740,1450,3150,83.333333,0.428571,23
3,3,3,Bukayo Saka,Arsenal,Premier League,Forward,25,6,10,65,1120,920,2100,82.142857,0.257143,16
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29
5,5,5,Bruno Fernandes,Manchester United,Premier League,Midfielder,36,8,10,104,2100,1680,3100,80.000000,0.232258,18
6,6,6,Kylian Mbappe,Real Madrid,La Liga,Forward,34,31,3,150,980,790,2900,80.612245,0.962069,34
7,7,7,Vinicius Junior,Real Madrid,La Liga,Forward,30,11,8,82,1050,840,2400,80.000000,0.412500,19
8,8,8,Jude Bellingham,Real Madrid,La Liga,Midfielder,31,9,8,70,1650,1450,2600,87.878788,0.311538,17
9,9,9,Lamine Yamal,Barcelona,La Liga,Forward,35,9,13,90,1600,1300,2850,81.250000,0.284211,22
10,10,10,Raphinha,Barcelona,La Liga,Forward,36,18,9,112,1450,1160,2900,80.000000,0.558621,27
11,11,11,Robert Lewandowski,Barcelona,La Liga,Forward,34,27,2,108,650,510,2750,78.461538,0.883636,29
12,12,12,Harry Kane,Bayern Munich,Bundesliga,Forward,31,26,8,110,1030,850,2700,82.524272,0.866667,34
13,13,13,Jamal Musiala,Bayern Munich,Bundesliga,Midfielder,25,12,3,68,1100,910,1900,82.727273,0.568421,15
14,14,14,Michael Olise,Bayern Munich,Bundesliga,Forward,34,12,15,91,1540,1270,2750,82.467532,0.392727,27
15,15,15,Florian Wirtz,Bayer Leverkusen,Bundesliga,Midfielder,31,10,12,75,1720,1410,2500,81.976744,0.360000,22
16,16,16,Serhou Guirassy,Borussia Dortmund,Bundesliga,Forward,30,21,3,87,620,480,2350,77.419355,0.804255,24
17,17,17,Patrik Schick,Bayer Leverkusen,Bundesliga,Forward,31,21,1,73,480,360,1900,75.000000,0.994737,22
18,18,18,Mateo Retegui,Atalanta,Serie A,Forward,36,25,8,102,590,440,2700,74.576271,0.833333,33
19,19,19,Marcus Thuram,Inter Milan,Serie A,Forward,36,14,4,81,760,590,2750,77.631579,0.458182,18
20,20,20,Lautaro Martinez,Inter Milan,Serie A,Forward,31,12,3,89,690,540,2350,78.260870,0.459574,15
21,21,21,Moise Kean,Fiorentina,Serie A,Forward,32,19,3,94,570,420,2500,73.684211,0.684000,22
22,22,22,Ademola Lookman,Atalanta,Serie A,Forward,31,15,5,88,820,640,2300,78.048780,0.586957,20
23,23,23,Ousmane Dembele,Paris Saint-Germain,Ligue 1,Forward,29,21,6,100,1250,1010,2200,80.800000,0.859091,27
24,24,24,Bradley Barcola,Paris Saint-Germain,Ligue 1,Forward,34,14,10,79,1120,900,2450,80.357143,0.514286,24

In [106]:
display(df.info()) #tells us info like each columns data type
df.describe()   #Displays a statistical summary of the numerical columns

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0.1        25 non-null     int64
 1   Unnamed: 0          25 non-null     int64
 2   Player              25 non-null     str
 3   Team                25 non-null     str
 4   League              25 non-null     str
 5   Position            25 non-null     str
 6   Matches             25 non-null     int64
 7   Goals               25 non-null     int64
 8   Assists             25 non-null     int64
 9   Shots               25 non-null     int64
 10  Passes_Attempted    25 non-null     int64
 11  Passes_Completed    25 non-null     int64
 12  Minutes             25 non-null     int64
 13  Pass_Accuracy       25 non-null     float64
 14  Goals_Per_90        25 non-null     float64
 15  Goal_Contributions  25 non-null     int64
dtypes: float64(2), int64(10), str(4)
memory usage: 3.3 KB

None

,Unnamed: 0.1,Unnamed: 0,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000,25.000000,25.000000
mean,12.000000,12.000000,32.480000,17.200000,7.160000,94.840000,1096.400000,884.400000,2600.04000,79.853116,0.598087,24.360000
std,7.359801,7.359801,3.355592,7.112196,4.346263,20.521696,453.448637,384.589391,366.72611,3.067525,0.235031,7.330757
min,0.000000,0.000000,25.000000,6.000000,1.000000,65.000000,480.000000,360.000000,1900.00000,73.684211,0.232258,15.000000
25%,6.000000,6.000000,31.000000,12.000000,3.000000,81.000000,690.000000,540.000000,2350.00000,78.048780,0.412500,19.000000
50%,12.000000,12.000000,32.000000,15.000000,8.000000,91.000000,1050.000000,850.000000,2700.00000,80.000000,0.568421,23.000000
75%,18.000000,18.000000,35.000000,22.000000,10.000000,105.000000,1450.000000,1160.000000,2773.00000,81.976744,0.804255,27.000000
max,24.000000,24.000000,38.000000,31.000000,18.000000,150.000000,2100.000000,1680.000000,3378.00000,87.878788,0.994737,47.000000

In [107]:
display(df.head()) #had to use display or print here because Jupyter only automatically displays the **last expression in a cell.
print("")
df.tail()

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
0,0,0,Mohamed Salah,Liverpool,Premier League,Forward,38,29,18,130,1450,1130,3378,77.931034,0.772647,47
1,1,1,Erling Haaland,Manchester City,Premier League,Forward,31,22,3,105,610,480,2773,78.688525,0.714028,25
2,2,2,Cole Palmer,Chelsea,Premier League,Midfielder,37,15,8,126,1740,1450,3150,83.333333,0.428571,23
3,3,3,Bukayo Saka,Arsenal,Premier League,Forward,25,6,10,65,1120,920,2100,82.142857,0.257143,16
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
20,20,20,Lautaro Martinez,Inter Milan,Serie A,Forward,31,12,3,89,690,540,2350,78.260870,0.459574,15
21,21,21,Moise Kean,Fiorentina,Serie A,Forward,32,19,3,94,570,420,2500,73.684211,0.684000,22
22,22,22,Ademola Lookman,Atalanta,Serie A,Forward,31,15,5,88,820,640,2300,78.048780,0.586957,20
23,23,23,Ousmane Dembele,Paris Saint-Germain,Ligue 1,Forward,29,21,6,100,1250,1010,2200,80.800000,0.859091,27
24,24,24,Bradley Barcola,Paris Saint-Germain,Ligue 1,Forward,34,14,10,79,1120,900,2450,80.357143,0.514286,24

In [108]:
df.shape #to tell you the row and column length

(25, 16)

In [109]:
display(df.isnull().sum())   #displays numbers of missing values for each column
df.duplicated()

Unnamed: 0.1          0
Unnamed: 0            0
Player                0
Team                  0
League                0
Position              0
Matches               0
Goals                 0
Assists               0
Shots                 0
Passes_Attempted      0
Passes_Completed      0
Minutes               0
Pass_Accuracy         0
Goals_Per_90          0
Goal_Contributions    0
dtype: int64

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [110]:
df["Pass_Accuracy"] = df["Passes_Completed"] / df["Passes_Attempted"] * 100
df["Goals_Per_90"] = df["Goals"] / df["Minutes"] * 90
df["Goal_Contributions"] = df["Goals"] + df["Assists"]

display(df)

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
0,0,0,Mohamed Salah,Liverpool,Premier League,Forward,38,29,18,130,1450,1130,3378,77.931034,0.772647,47
1,1,1,Erling Haaland,Manchester City,Premier League,Forward,31,22,3,105,610,480,2773,78.688525,0.714028,25
2,2,2,Cole Palmer,Chelsea,Premier League,Midfielder,37,15,8,126,1740,1450,3150,83.333333,0.428571,23
3,3,3,Bukayo Saka,Arsenal,Premier League,Forward,25,6,10,65,1120,920,2100,82.142857,0.257143,16
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29
5,5,5,Bruno Fernandes,Manchester United,Premier League,Midfielder,36,8,10,104,2100,1680,3100,80.000000,0.232258,18
6,6,6,Kylian Mbappe,Real Madrid,La Liga,Forward,34,31,3,150,980,790,2900,80.612245,0.962069,34
7,7,7,Vinicius Junior,Real Madrid,La Liga,Forward,30,11,8,82,1050,840,2400,80.000000,0.412500,19
8,8,8,Jude Bellingham,Real Madrid,La Liga,Midfielder,31,9,8,70,1650,1450,2600,87.878788,0.311538,17
9,9,9,Lamine Yamal,Barcelona,La Liga,Forward,35,9,13,90,1600,1300,2850,81.250000,0.284211,22
10,10,10,Raphinha,Barcelona,La Liga,Forward,36,18,9,112,1450,1160,2900,80.000000,0.558621,27
11,11,11,Robert Lewandowski,Barcelona,La Liga,Forward,34,27,2,108,650,510,2750,78.461538,0.883636,29
12,12,12,Harry Kane,Bayern Munich,Bundesliga,Forward,31,26,8,110,1030,850,2700,82.524272,0.866667,34
13,13,13,Jamal Musiala,Bayern Munich,Bundesliga,Midfielder,25,12,3,68,1100,910,1900,82.727273,0.568421,15
14,14,14,Michael Olise,Bayern Munich,Bundesliga,Forward,34,12,15,91,1540,1270,2750,82.467532,0.392727,27
15,15,15,Florian Wirtz,Bayer Leverkusen,Bundesliga,Midfielder,31,10,12,75,1720,1410,2500,81.976744,0.360000,22
16,16,16,Serhou Guirassy,Borussia Dortmund,Bundesliga,Forward,30,21,3,87,620,480,2350,77.419355,0.804255,24
17,17,17,Patrik Schick,Bayer Leverkusen,Bundesliga,Forward,31,21,1,73,480,360,1900,75.000000,0.994737,22
18,18,18,Mateo Retegui,Atalanta,Serie A,Forward,36,25,8,102,590,440,2700,74.576271,0.833333,33
19,19,19,Marcus Thuram,Inter Milan,Serie A,Forward,36,14,4,81,760,590,2750,77.631579,0.458182,18
20,20,20,Lautaro Martinez,Inter Milan,Serie A,Forward,31,12,3,89,690,540,2350,78.260870,0.459574,15
21,21,21,Moise Kean,Fiorentina,Serie A,Forward,32,19,3,94,570,420,2500,73.684211,0.684000,22
22,22,22,Ademola Lookman,Atalanta,Serie A,Forward,31,15,5,88,820,640,2300,78.048780,0.586957,20
23,23,23,Ousmane Dembele,Paris Saint-Germain,Ligue 1,Forward,29,21,6,100,1250,1010,2200,80.800000,0.859091,27
24,24,24,Bradley Barcola,Paris Saint-Germain,Ligue 1,Forward,34,14,10,79,1120,900,2450,80.357143,0.514286,24

In [111]:
display(df[df["Goals"] >= 15])
display(df[df["Pass_Accuracy"] > 80])
display(df[(df["Position"] == "Forward") & (df["Minutes"] > 2600)])

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
0,0,0,Mohamed Salah,Liverpool,Premier League,Forward,38,29,18,130,1450,1130,3378,77.931034,0.772647,47
1,1,1,Erling Haaland,Manchester City,Premier League,Forward,31,22,3,105,610,480,2773,78.688525,0.714028,25
2,2,2,Cole Palmer,Chelsea,Premier League,Midfielder,37,15,8,126,1740,1450,3150,83.333333,0.428571,23
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29
6,6,6,Kylian Mbappe,Real Madrid,La Liga,Forward,34,31,3,150,980,790,2900,80.612245,0.962069,34
10,10,10,Raphinha,Barcelona,La Liga,Forward,36,18,9,112,1450,1160,2900,80.000000,0.558621,27
11,11,11,Robert Lewandowski,Barcelona,La Liga,Forward,34,27,2,108,650,510,2750,78.461538,0.883636,29
12,12,12,Harry Kane,Bayern Munich,Bundesliga,Forward,31,26,8,110,1030,850,2700,82.524272,0.866667,34
16,16,16,Serhou Guirassy,Borussia Dortmund,Bundesliga,Forward,30,21,3,87,620,480,2350,77.419355,0.804255,24
17,17,17,Patrik Schick,Bayer Leverkusen,Bundesliga,Forward,31,21,1,73,480,360,1900,75.000000,0.994737,22
18,18,18,Mateo Retegui,Atalanta,Serie A,Forward,36,25,8,102,590,440,2700,74.576271,0.833333,33
21,21,21,Moise Kean,Fiorentina,Serie A,Forward,32,19,3,94,570,420,2500,73.684211,0.684000,22
22,22,22,Ademola Lookman,Atalanta,Serie A,Forward,31,15,5,88,820,640,2300,78.048780,0.586957,20
23,23,23,Ousmane Dembele,Paris Saint-Germain,Ligue 1,Forward,29,21,6,100,1250,1010,2200,80.800000,0.859091,27

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
2,2,2,Cole Palmer,Chelsea,Premier League,Midfielder,37,15,8,126,1740,1450,3150,83.333333,0.428571,23
3,3,3,Bukayo Saka,Arsenal,Premier League,Forward,25,6,10,65,1120,920,2100,82.142857,0.257143,16
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29
6,6,6,Kylian Mbappe,Real Madrid,La Liga,Forward,34,31,3,150,980,790,2900,80.612245,0.962069,34
8,8,8,Jude Bellingham,Real Madrid,La Liga,Midfielder,31,9,8,70,1650,1450,2600,87.878788,0.311538,17
9,9,9,Lamine Yamal,Barcelona,La Liga,Forward,35,9,13,90,1600,1300,2850,81.250000,0.284211,22
12,12,12,Harry Kane,Bayern Munich,Bundesliga,Forward,31,26,8,110,1030,850,2700,82.524272,0.866667,34
13,13,13,Jamal Musiala,Bayern Munich,Bundesliga,Midfielder,25,12,3,68,1100,910,1900,82.727273,0.568421,15
14,14,14,Michael Olise,Bayern Munich,Bundesliga,Forward,34,12,15,91,1540,1270,2750,82.467532,0.392727,27
15,15,15,Florian Wirtz,Bayer Leverkusen,Bundesliga,Midfielder,31,10,12,75,1720,1410,2500,81.976744,0.360000,22
23,23,23,Ousmane Dembele,Paris Saint-Germain,Ligue 1,Forward,29,21,6,100,1250,1010,2200,80.800000,0.859091,27
24,24,24,Bradley Barcola,Paris Saint-Germain,Ligue 1,Forward,34,14,10,79,1120,900,2450,80.357143,0.514286,24

,Unnamed: 0.1,Unnamed: 0,Player,Team,League,Position,Matches,Goals,Assists,Shots,Passes_Attempted,Passes_Completed,Minutes,Pass_Accuracy,Goals_Per_90,Goal_Contributions
0,0,0,Mohamed Salah,Liverpool,Premier League,Forward,38,29,18,130,1450,1130,3378,77.931034,0.772647,47
1,1,1,Erling Haaland,Manchester City,Premier League,Forward,31,22,3,105,610,480,2773,78.688525,0.714028,25
4,4,4,Alexander Isak,Newcastle United,Premier League,Forward,34,23,6,92,720,580,2750,80.555556,0.752727,29
6,6,6,Kylian Mbappe,Real Madrid,La Liga,Forward,34,31,3,150,980,790,2900,80.612245,0.962069,34
9,9,9,Lamine Yamal,Barcelona,La Liga,Forward,35,9,13,90,1600,1300,2850,81.250000,0.284211,22
10,10,10,Raphinha,Barcelona,La Liga,Forward,36,18,9,112,1450,1160,2900,80.000000,0.558621,27
11,11,11,Robert Lewandowski,Barcelona,La Liga,Forward,34,27,2,108,650,510,2750,78.461538,0.883636,29
12,12,12,Harry Kane,Bayern Munich,Bundesliga,Forward,31,26,8,110,1030,850,2700,82.524272,0.866667,34
14,14,14,Michael Olise,Bayern Munich,Bundesliga,Forward,34,12,15,91,1540,1270,2750,82.467532,0.392727,27
18,18,18,Mateo Retegui,Atalanta,Serie A,Forward,36,25,8,102,590,440,2700,74.576271,0.833333,33
19,19,19,Marcus Thuram,Inter Milan,Serie A,Forward,36,14,4,81,760,590,2750,77.631579,0.458182,18

In [112]:
#have to set to a new variable because groupby makes new object
positions_goals= df.groupby("Position")
display(positions_goals["Goals"].mean())

Position
Forward       18.8
Midfielder    10.8
Name: Goals, dtype: float64

In [113]:
teams_goals = df.groupby(["Team"])
display(teams_goals["Goals"].sum())

Team
Arsenal                 6
Atalanta               40
Barcelona              54
Bayer Leverkusen       31
Bayern Munich          50
Borussia Dortmund      21
Chelsea                15
Fiorentina             19
Inter Milan            26
Liverpool              29
Manchester City        22
Manchester United       8
Newcastle United       23
Paris Saint-Germain    35
Real Madrid            51
Name: Goals, dtype: int64

In [114]:
#you have to save this df cause the old version doesn't have pass accuracy
df.to_csv("futball.csv", index=False)
team_pass_accuracy = df.groupby(["Team"])
display(team_pass_accuracy["Pass_Accuracy"].mean())

Team
Arsenal                82.142857
Atalanta               76.312526
Barcelona              79.903846
Bayer Leverkusen       78.488372
Bayern Munich          82.573026
Borussia Dortmund      77.419355
Chelsea                83.333333
Fiorentina             73.684211
Inter Milan            77.946224
Liverpool              77.931034
Manchester City        78.688525
Manchester United      80.000000
Newcastle United       80.555556
Paris Saint-Germain    80.578571
Real Madrid            82.830344
Name: Pass_Accuracy, dtype: float64